language: c
compiler:
   - clang
   - gcc
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y libpcap-dev
   - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz -O /tmp/cmocka-1.0.1.tar.xz
   - tar -xvf /tmp/cmocka-1.0.1.tar.xz
   - cd cmocka-1.0.1 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_STATIC_LIB=OFF -DUNIT_TESTING=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=ON .. && make && sudo make install
script: ./autogen.sh --disable-linux-kernel-module --disable-doc && make clean && make all && make check && make distcheck
